[main]
data_path = ["data", "."]
music_path = "data"
sound_path = "data"
save_path = "data"
fonts = ["data/font/english.ttf", "data/font/chinese.ttf"]
ship_logic_enabled = true

[window]
width = 640
height = 480

[ui]
simplified_chinese = false
no_name_input = false
show_potential = true
scale = 2.0
animation_speed = 1.0
fade_speed = 1.0
