[main]
data_path = ["data", "."]
music_path = "data"
sound_path = "data"
save_path = "data"
fonts = "data/font/chinese.otf"
ship_logic_enabled = true

[window]
width = 1024
height = 640
show_fps = false
limit_fps = 0

[ui]
simplified_chinese = false
no_name_input = false
show_potential = true
show_map_mini_panel = true
show_minimap = true
scale = 2.0
animation_speed = 1.0
fade_speed = 1.0
window_border = 8

[audio]
# dosbox - Default value, from DOSBox 0.74, well-accurate and fast, use it for low-end CPUs
# nuked174 - Nuked OPL3 v1.7.4, very accurate but needs more CPU power
# nuked - Nuked OPL3 v1.8, latest version
opl_emulator = "dosbox"
sample_rate = 48000
# For soxr resampler: I16 = sint16, I32 = sint32, F32 = float
# For zita resampler: this option is ignored, sample format is always F32
sample_format = "I16"
music_volume = 5
sound_volume = 5
