strings = [
    # 0
    "徐小俠",
    "生命點數",
    "最大生命點數",
    "中毒程度",
    "體力",
    # 5
    "內力性質",
    "內力點數",
    "最大内力點數",
    "攻擊力",
    "輕功",
    # 10
    "防御力",
    "醫療能力",
    "用毒能力",
    "解毒能力",
    "抗毒能力",
    # 15
    "拳掌功夫",
    "御劍能力",
    "耍刀技巧",
    "特殊兵器",
    "暗器技巧",
    # 20
    "武學常識",
    "道德",
    "左右互搏",
    "功夫帶毒",
    "等級",
    # 25
    "生命",
    "內力",
    "經驗",
    "升級",
    "資質",
    # 30
    "所會功夫",
    "裝備物品",
    "修練物品",
    "增加",
    "提昇",
    # 35
    "減少",
    "誰要使用",
    "使用",
    "誰要配備",
    "誰要修練",
    # 40
    "人 ({0},{1})  船 ({2},{3})",
    "請輸入姓名：",
    "一人只能修練十種功夫",
    "此人不適合修練此物品",
    "此物品現在已經有人修練了",
    # 45
    "是否要換人修練？",
    "此人不適合配備此物品",
    "醫療",
    "解毒",
    "物品",
    # 50
    "狀態",
    "離隊",
    "系統",
    "誰要使用醫術",
    "要醫治誰",
    # 55,
    "恢復生命",
    "誰要幫人解毒",
    "替誰解毒",
    "幫助解毒",
    "要查閱誰的狀態",
    # 60
    "要求誰離隊",
    "抱歉，沒有你遊戲進行不下去",
    "讀檔",
    "存檔",
    "離開",
    # 65
    "一",
    "二",
    "三",
    "存檔完成",
    "讀檔失敗",
    # 70
    "請選擇參與戰鬥之人物",
    "獲得",
    "是否與之過招？",
    "是否要求加入？",
    "請選擇是或否？",
    # 75
    "習得武學",
    "你的道德指數為",
    "你的聲望指數為",
    "是",
    "否",
    # 80
    "結束",
    "{0} 升級為 第 {1} 級",
    "移動",
    "攻擊",
    "用毒",
    # 85
    "解毒",
    "醫療",
    "物品",
    "等待",
    "狀態",
    # 90
    "休息",
    "自動",
    "選擇攻擊方向",
    "戰鬥勝利",
    "戰鬥失敗",
    # 95
    "{0} 獲得經驗點數 {1}",
    "{0} 升級了",
    "{0} 修練 {1} 成功",
    "{0} 升級為 第 {1} 級",
    "{0} 製造出 {1}",
    #100
    "這樣的屬性滿意嗎？",
    "武力",
    "防禦",
    "醫療",
    "使毒",
    #105
    "解毒",
    "拳掌",
    "劍術",
    "刀術",
    "暗器",
    #110
    "居",
    "在地球的某處",
    "當地人口的失蹤數",
    "又多了一筆………",
    "聲望",
    #115,
    "沒有可以使用的功夫",
]
